name: Deploy to GitHub Pages

# Trigger only when pushing to the production branch
on:
  push:
    branches:
      - production   # Only deploy on push to production branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Snyk CLI
      - name: Set up Snyk CLI
        uses: snyk/actions/setup@v2
        with:
          version: 'latest'  # You can specify a version or use 'latest'

      # Step 3: Run Snyk to check for vulnerabilities
      - name: Run Snyk to check for vulnerabilities
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  # Make sure to add your Snyk token to GitHub Secrets

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # The directory where your static files are located (root for HTML/CSS files)
