name: Snyk Security Scan

on:
  push:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Snyk Security Scan
        uses: snyk/actions/node@master  # Replace with the correct Snyk action for your language if needed
        with:
          args: test  # Use `monitor` if you want continuous monitoring
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
