name: Deploy to GitHub Pages

# Trigger only when pushing to the production branch
on:
  push:
    branches:
      - production   # renamed from master Only deploy on push to production branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2
 # Dependency scanning using Snyk 
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/setup@v2
        with:
          args: test
      # Step 2: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{snyk_code}}
          publish_dir: ./  # The directory where your static files are located (root for HTML/CSS files)
