name: Lint HTML and CSS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install HTMLHint and Stylelint
      - name: Install HTMLHint and Stylelint
        run: |
          npm install -g htmlhint
          npm install -g stylelint stylelint-config-standard

      # Step 4: Add Stylelint Configuration File
      - name: Add Stylelint Configuration
        run: |
          echo '{
            "extends": "stylelint-config-standard",
            "rules": {
              "alpha-value-notation": "percentage",
              "color-function-notation": "modern",
              "selector-class-pattern": "^[a-z0-9\\-]+$",
              "comment-whitespace-inside": "always",
              "length-zero-no-unit": true,
              "no-duplicate-selectors": true,
              "declaration-empty-line-before": "never",
              "comment-empty-line-before": "always"
            }
          }' > .stylelintrc.json

      # Step 5: Run HTMLHint for HTML linting
      - name: Run HTMLHint
        run: htmlhint "**/*.html"

      # Step 6: Run Stylelint for CSS linting with auto-fix
      - name: Run Stylelint
        run: stylelint "**/*.css" --fix

      # Step 7: Verify the repository status
      - name: Check for changes after auto-fix
        run: |
          git status
          git diff
