name: Lint HTML and CSS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install HTMLHint and Stylelint
        run: |
          npm install -g htmlhint
          npm install -g stylelint stylelint-config-standard

      - name: Add Stylelint Configuration
        run: |
          echo '{
            "extends": "stylelint-config-standard",
            "rules": {
              "alpha-value-notation": "percentage",
              "color-function-notation": "modern",
              "selector-class-pattern": "^[a-z0-9\\-]+$",
              "comment-whitespace-inside": "always",
              "length-zero-no-unit": true,
              "no-duplicate-selectors": true,
              "declaration-empty-line-before": "never",
              "comment-empty-line-before": "always"
            }
          }' > .stylelintrc.json

      - name: Run HTMLHint
        run: htmlhint "**/*.html" > htmlhint-report.txt

      - name: Run Stylelint
        run: stylelint "**/*.css" --fix > stylelint-report.txt

      - name: Check for changes after auto-fix
        run: |
          git status
          git diff

      - name: Commit changes made by auto-fix
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Stylelint auto-fix"
          git push
        if: success()

      - name: Upload lint reports
        uses: actions/upload-artifact@v3
        with:
          name: lint-reports
          path: |
            htmlhint-report.txt
            stylelint-report.txt
